# Essentials
profile=gpu-hq
vo=gpu-next
hwdec-codecs=all
fbo-format=rgba32f
input-default-bindings=no
hr-seek-framedrop=no
keep-open=always
reset-on-next-file=pause
window-dragging=no
save-watch-history=yes
force-seekable=yes
input-ipc-server=/tmp/mpv-socket

# OSC
border=yes
osd-bar=no
geometry=75%x75%
taskbar-progress=no
cursor-autohide=1000
script-opts=osc-layout=bottombar,osc-seekbarstyle=bar,ost-windowcontrols=no

# Deband
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=20
deband-grain=5

# Scaling
scale=ewa_lanczos
dscale=mitchell
cscale=spline36
scale-blur=0.981251
correct-downscaling=yes
linear-upscaling=yes
sigmoid-upscaling=yes

# Dither
dither-depth=auto

# Interpolation
interpolation=yes
video-sync=display-resample

# Audio
volume=100
volume-max=300
audio-stream-silence=yes

# Subtitles
sub-auto=fuzzy
demuxer-mkv-subtitle-preroll=yes
sub-ass-use-video-data=all
sub-fix-timing=yes
sub-gauss=0.5
sub-gray=yes
sub-font='Trebuchet MS'
sub-bold=yes

# Language
alang=Japanese,jap,jp,jpn,English,en,eng
slang=English,en,eng,enUS

# Screenshots
screenshot-format=jpeg
screenshot-high-bit-depth=yes
screenshot-jpeg-quality=100
screenshot-template="%F-%wH.%wM.%wS.%wT"
screenshot-directory=~/Pictures/mpv/

# youtube-dl
ytdl-format="bestvideo[height<=?1080]+bestaudio/best"
demuxer-max-bytes=150000000
demuxer-max-back-bytes=75000000
force-seekable=yes

# Profiles
[extension.gif]
loop-file=inf
